### PR TITLE
Possibility to use hierarchical JSON ({"ONE": {"TWO": "Something"}} call...

### PR DESCRIPTION
**Pull request by ZorGleH**
Hi,

I've made some improvement for my own needs. Feel free to merge them or not. Here are the changes:
- Possibility to use hierarchical JSON ({"ONE": {"TWO": "Something"}} called with "ONE.TWO" key, unlimited levels).
- Wrap missing translations in a span with class "missing-translation" (put a red background on them and you've got something perfect for non-developers who want to help you translate a big application).

### CODE REVIEW

**Comment by ZorGleH** [comment]
I've done the tests on my master branch but can't figure how to make a new PR, do you know how to do that?

**Comment by StephanHoyer** [comment]
As you see, the pullrequest will be updated automatically. Sadly, travis currently has some problems

Can you please update the .travis.yml to use node version 0.8 instead of 0.8.11?

https://github.com/ZorGleH/ng-translate/blob/master/.travis.yml

Thanks for the great work so far.

**Comment by ZorGleH** [comment]
Done.

**Comment by StephanHoyer** [comment]
Thanks for contributing.

I will update the bower package as soon as I have some time. I would like to get some small things strait before doing this.

**Comment by ZorGleH** [comment]
Thank you.

2014-06-25 16:38 GMT+02:00 Stephan Hoyer notifications@github.com:

> Thanks for contributing.
> 
> I will update the bower package as soon as I have some time. I would like
> to get some small things strait before doing this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephanHoyer/ng-translate/pull/7#issuecomment-47109528
> .

## 

Grégoire Dubourg
1084 rue de Paris
60520 La Chapelle-en-Serval
06 82 36 45 23
09 53 89 43 54

**Pull request merged**
